### ISSUE TITLE
Startup fails with following message: Requiring namespace 'Gtk' version '2.0', but '3.0' is already loaded

### ISSUE THREAD

**Issue by nostra** [nitipit/markdo#1]
Installation went well under gentoo linux with python-2.7.3 as root user.

Startup failed with the following message:

```
Traceback (most recent call last):
  File "/usr/bin/markdo", line 3, in <module>
    from markdo import app
  File "/usr/lib/python2.7/site-packages/markdo/app.py", line 2, in <module>
    from gi.repository import Gtk, WebKit, Soup
  File "/usr/lib/python2.7/site-packages/gi/importer.py", line 76, in load_module
    dynamic_module._load()
  File "/usr/lib/python2.7/site-packages/gi/module.py", line 222, in _load
    version)
  File "/usr/lib/python2.7/site-packages/gi/module.py", line 90, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '2.0', but '3.0' is already loaded

```

**Comment by nitipit** [comment]
I'm trying to install gentoo now :)

**Comment by nitipit** [comment]
It works fine on my pc, gentoo 12.1 on virtual-machine, didn't see any errors
[screenshot](https://raw.github.com/nitipit/markdo/master/doc/gentoo-screenshot.png)

**Comment by nostra** [comment]
I have tested this on my home computer (which also is gentoo), and I did not encounter any problems. There is probably something strange on my work computer. Let me check more thoroughly, and get back with what I discover.
